name: ECUAMAPS PRO - Generador de APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

jobs:
  build:
    name: Compilar APK Nativa
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build cmake g++-multilib

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 200

      - name: Parallel submodules checkout
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure repository
        run: ./configure.sh

      - name: Compilar WebDebug (EG Focus)
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -Parm64 assembleWebDebug --stacktrace

      - name: Entregar APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ecuamaps-pro-apk
          path: android/app/build/outputs/apk/**/ecuamaps-*.apk
          if-no-files-found: error
